create table release_note_templates
(
    id          uuid                     not null
        primary key,
    key         varchar(50)              not null
        unique,
    name        varchar(200)             not null,
    description varchar(500),
    sections    jsonb   default '[]'::jsonb,
    styling     jsonb   default '{"showDate": true, "fontFamily": "system-ui", "showVersion": true, "primaryColor": "#1e40af", "showItemIcons": true}'::jsonb,
    is_active   boolean default true,
    sort_order  integer default 0,
    created_at  timestamp with time zone not null,
    updated_at  timestamp with time zone not null,
    deleted_at  timestamp with time zone
);

alter table release_note_templates
    owner to db1usr;

INSERT INTO public.release_note_templates (id, key, name, description, sections, styling, is_active, sort_order, created_at, updated_at, deleted_at) VALUES ('05fe5c2c-bc75-4c8b-990a-69d966331de2', 'standard', 'Standard Changelog', 'Complete changelog with all sections - ideal for developer documentation', '[{"key": "summary", "label": "Summary", "itemTypes": [], "isRequired": false, "showDescriptions": true}, {"key": "features", "label": "New Features", "itemTypes": ["feature"], "isRequired": false, "showDescriptions": true}, {"key": "improvements", "label": "Improvements", "itemTypes": ["improvement"], "isRequired": false, "showDescriptions": true}, {"key": "bugfixes", "label": "Bug Fixes", "itemTypes": ["bugfix"], "isRequired": false, "showDescriptions": true}, {"key": "breaking", "label": "Breaking Changes", "itemTypes": ["breaking"], "isRequired": false, "showDescriptions": true}, {"key": "deprecations", "label": "Deprecations", "itemTypes": ["deprecation", "deprecated"], "isRequired": false, "showDescriptions": true}, {"key": "security", "label": "Security", "itemTypes": ["security"], "isRequired": false, "showDescriptions": true}, {"key": "performance", "label": "Performance", "itemTypes": ["performance"], "isRequired": false, "showDescriptions": true}, {"key": "docs", "label": "Documentation", "itemTypes": ["docs"], "isRequired": false, "showDescriptions": true}]', '{"showDate": true, "fontFamily": "system-ui", "headerStyle": "gradient", "showVersion": true, "primaryColor": "#1e40af", "showItemIcons": true, "secondaryColor": "#3b82f6", "showProductName": true}', true, 1, '2026-01-15 12:01:06.414000 +00:00', '2026-01-15 12:01:06.414000 +00:00', null);
INSERT INTO public.release_note_templates (id, key, name, description, sections, styling, is_active, sort_order, created_at, updated_at, deleted_at) VALUES ('98df7e52-4598-4366-9a5a-6b6ac75bea1e', 'customer', 'Customer-Facing', 'Simplified release notes for customers - hides technical details', '[{"key": "summary", "label": "What''s New", "itemTypes": [], "isRequired": false, "showDescriptions": true}, {"key": "features", "label": "New Features", "itemTypes": ["feature"], "isRequired": false, "showDescriptions": true}, {"key": "improvements", "label": "Improvements", "itemTypes": ["improvement"], "isRequired": false, "showDescriptions": false}, {"key": "bugfixes", "label": "Fixes", "itemTypes": ["bugfix"], "isRequired": false, "showDescriptions": false}]', '{"showDate": true, "fontFamily": "system-ui", "headerStyle": "clean", "showVersion": true, "primaryColor": "#059669", "showItemIcons": false, "secondaryColor": "#10b981", "showProductName": true}', true, 2, '2026-01-15 12:01:06.479000 +00:00', '2026-01-15 12:01:06.479000 +00:00', null);
INSERT INTO public.release_note_templates (id, key, name, description, sections, styling, is_active, sort_order, created_at, updated_at, deleted_at) VALUES ('3eda1993-f337-4a33-a965-f06e7fbb9fce', 'internal', 'Internal Technical', 'Detailed technical release notes for internal teams with all details', '[{"key": "summary", "label": "Overview", "itemTypes": [], "isRequired": false, "showDescriptions": true}, {"key": "breaking", "label": "Breaking Changes", "itemTypes": ["breaking"], "isRequired": false, "showDescriptions": true}, {"key": "security", "label": "Security Updates", "itemTypes": ["security"], "isRequired": false, "showDescriptions": true}, {"key": "features", "label": "Features", "itemTypes": ["feature"], "isRequired": false, "showDescriptions": true}, {"key": "improvements", "label": "Improvements", "itemTypes": ["improvement"], "isRequired": false, "showDescriptions": true}, {"key": "performance", "label": "Performance", "itemTypes": ["performance"], "isRequired": false, "showDescriptions": true}, {"key": "bugfixes", "label": "Bug Fixes", "itemTypes": ["bugfix"], "isRequired": false, "showDescriptions": true}, {"key": "deprecations", "label": "Deprecations", "itemTypes": ["deprecation", "deprecated"], "isRequired": false, "showDescriptions": true}, {"key": "docs", "label": "Documentation", "itemTypes": ["docs"], "isRequired": false, "showDescriptions": true}]', '{"showDate": true, "fontFamily": "monospace", "headerStyle": "technical", "showVersion": true, "primaryColor": "#7c3aed", "showItemIcons": true, "secondaryColor": "#8b5cf6", "showProductName": true}', true, 3, '2026-01-15 12:01:06.549000 +00:00', '2026-01-15 12:01:06.549000 +00:00', null);
